DROP DATABASE ACTIVIDAD1;
CREATE DATABASE ACTIVIDAD1;
USE ACTIVIDAD1;

-- FABRICANTES - ARTICULOS

CREATE TABLE FABRICANTE (
	CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (CODIGO)
);

CREATE TABLE ARTICULO(
	CODIGO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO INT NOT NULL,
    FABRICANTE INT NOT NULL,
    
    PRIMARY KEY (CODIGO),
    
    FOREIGN KEY (FABRICANTE) REFERENCES FABRICANTE(CODIGO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);



-- EMPLEADOS - DEPARTAMENTOS

CREATE TABLE DEPARTAMENTO(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRESUPUESTO INT NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE EMPLEADO(
	DNI VARCHAR(8) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DEPARTAMENTO INT NOT NULL,
    
    PRIMARY KEY (DNI),
    
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);


-- ALMACENES - CAJAS

CREATE TABLE ALMACEN(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    LUGAR VARCHAR(100) NOT NULL,
    CAPACIDAD INT NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE CAJA(
	NUM_REFERENCIA CHAR(5) NOT NULL,
    CONTENIDO VARCHAR(100) NOT NULL,
    VALOR INT NOT NULL,
    ALMACEN INT NOT NULL,
    
    PRIMARY KEY(NUM_REFERENCIA),
    
    FOREIGN KEY(ALMACEN) REFERENCES ALMACEN(CODIGO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);


-- SALAS - PELICULAS

CREATE TABLE PELICULA(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    CALIFICACION_EDAD INT(2) NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE SALA(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PELICULA INT,
    
    PRIMARY KEY(CODIGO),
    
    FOREIGN KEY(PELICULA) REFERENCES PELICULA(CODIGO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- PIEZAS - PROVEEDORES

CREATE TABLE PIEZA(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE PROVEEDOR(
	ID CHAR(4) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    
    PRIMARY KEY(ID)
);

CREATE TABLE SUMINISTRA(
	CODIGO_PIEZA INT NOT NULL AUTO_INCREMENT,
    ID_PROVEEDOR CHAR(4) NOT NULL,
    PRECIO INT NOT NULL,
    
    PRIMARY KEY(CODIGO_PIEZA, ID_PROVEEDOR),
    
    FOREIGN KEY(CODIGO_PIEZA) REFERENCES PIEZA(CODIGO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    
    FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- CIENTIFICOS

CREATE TABLE CIENTIFICO(
	DNI VARCHAR(8) NOT NULL,
    NOM_APELLI VARCHAR(255) NOT NULL,
    
    PRIMARY KEY(DNI)
);

CREATE TABLE PROYECTO(
	ID CHAR(4) NOT NULL,
    NOMBRE VARCHAR(255),
    HORA INT,
    
    PRIMARY KEY (ID)
);

CREATE TABLE ASIGNADO_A(
	CIENTIFICO VARCHAR(8) NOT NULL,
    PROYECTO CHAR(4) NOT NULL,
    
    PRIMARY KEY(CIENTIFICO, PROYECTO),
    
    FOREIGN KEY(CIENTIFICO) REFERENCES CIENTIFICO(DNI)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    
    FOREIGN KEY(PROYECTO) REFERENCES PROYECTO(ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);



-- GRANDES AMAZENES

CREATE TABLE CAJERO(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOM_APELLI VARCHAR(255) NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE PRODUCTO(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO INT NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE MAQUINAS_REGISTRADORAS(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    PISO INT NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE VENTA(
	CAJERO INT NOT NULL,
    MAQUINA INT NOT NULL,
    PRODUCTO INT NOT NULL,
    
    PRIMARY KEY(CAJERO, MAQUINA, PRODUCTO),
    
    FOREIGN KEY(CAJERO) REFERENCES CAJERO(CODIGO)
	ON DELETE RESTRICT
    ON UPDATE CASCADE,
    
    FOREIGN KEY(MAQUINA) REFERENCES MAQUINAS_REGISTRADORAS(CODIGO)
	ON DELETE RESTRICT
    ON UPDATE CASCADE,

	FOREIGN KEY(PRODUCTO) REFERENCES PRODUCTO(CODIGO)
	ON DELETE RESTRICT
    ON UPDATE CASCADE
);


-- INVESTIGADORES

CREATE TABLE FACULTAD(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    
    PRIMARY KEY(CODIGO)
);

CREATE TABLE EQUIPO(
	NUM_SERIE CHAR(4) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    FACULTAD INT NOT NULL,
    
    PRIMARY KEY(NUM_SERIE),
    
    FOREIGN KEY(FACULTAD) REFERENCES FACULTAD(CODIGO)
	ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE INVESTIGADOR(
	DNI VARCHAR(8) NOT NULL,
    NOM_APELLI VARCHAR(255) NOT NULL,
    FACULTAD INT NOT NULL,
    
    PRIMARY KEY(DNI),
    
    FOREIGN KEY(FACULTAD) REFERENCES FACULTAD(CODIGO)
	ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE RESERVA(
	DNI VARCHAR(8) NOT NULL,
    NUM_SERIE CHAR(4) NOT NULL,
	COMIENZO DATETIME NOT NULL,
    FIN DATETIME NOT NULL,
    
    PRIMARY KEY(DNI, NUM_SERIE),
    
    FOREIGN KEY(DNI) REFERENCES INVESTIGADOR(DNI)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
    
    FOREIGN KEY(NUM_SERIE) REFERENCES EQUIPO(NUM_SERIE)
	ON DELETE CASCADE
    ON UPDATE CASCADE
);