CREATE DATABASE prova; -- crea

DROP DATABASE prova; -- borra

USE prova;

CREATE TABLE TAULAPROVA (
	ID INT NOT NULL AUTO_INCREMENT,
    COLUMNASTRING VARCHAR(32) NOT NULL DEFAULT '',
    COLUMNACHAR CHAR(1),
    COLUMNAINT INT(2) DEFAULT 0,
    COLUMNAFLOAT FLOAT(5,2),
    COLUMNADOUBLE DOUBLE(5,2),
    COLUMNADECIMAL DECIMAL(4,2),
    COLDATE DATE,
    COLDATETIME DATETIME,
    COLTIMESTAMP TIMESTAMP,
    
    PRIMARY KEY (ID)
);

SHOW TABLES;

DROP TABLE TAULAPROVA;

-- ------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE LLIBRE(
	IDLLIBRE INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(32) NOT NULL,
    IDAUTOR INT NOT NULL,
    
    PRIMARY KEY (IDLLIBRE),
    
    FOREIGN KEY (IDAUTOR) REFERENCES AUTOR(IDAUTOR) 
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE AUTOR(
	IDAUTOR INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(32) NOT NULL,
    
    PRIMARY KEY (IDAUTOR)
);



SELECT * FROM AUTOR;

INSERT INTO AUTOR(NOM) VALUES('JOSE');
INSERT INTO AUTOR(NOM) VALUES('IRENE');
INSERT INTO AUTOR(NOM) VALUES('PEDRO');

INSERT INTO LLIBRE(NOM, IDAUTOR) VALUES('LLIBRE IRENE 2', 2);
 
SELECT * FROM AUTOR;

UPDATE AUTOR SET NOM = 'IRENE2' WHERE IDAUTOR = '2';

DELETE FROM AUTOR WHERE IDAUTOR = 3; 

