/*AUTOR I LLIBRE*/
DESCRIBE AUTOR;

DESCRIBE LLIBRE;

SELECT L.* 
FROM 
	AUTOR A, 
    LLIBRE L
WHERE 
	A.IDAUTOR = L.IDAUTOR AND
    A.IDAUTOR = 1;
    
    
/***************************************************/
CREATE TABLE MOVIE(
	ID_MOVIE INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(32) NOT NULL
);


CREATE TABLE ACTOR(
	ID_ACTOR INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL
);

CREATE TABLE MOVIE_ACTOR(
	ID_MOVIE INT NOT NULL,
    ID_ACTOR INT NOT NULL,
    
    PRIMARY KEY(ID_MOVIE,ID_ACTOR),
    FOREIGN KEY(ID_MOVIE) REFERENCES MOVIE(ID_MOVIE) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_ACTOR) REFERENCES ACTOR(ID_ACTOR) ON DELETE CASCADE ON UPDATE CASCADE

);


SELECT * FROM MOVIE;