DROP DATABASE SHOP;
CREATE DATABASE SHOP;
USE SHOP;

CREATE TABLE CATEGORY(
	CODE INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    
    PRIMARY KEY (CODE)
);

INSERT INTO CATEGORY(NAME) VALUES ('COMPUTER');
INSERT INTO CATEGORY(NAME) VALUES ('TV');
INSERT INTO CATEGORY(NAME) VALUES ('TABLETS');
INSERT INTO CATEGORY(NAME) VALUES ('PHONES');

-- -------------------------------------------------

CREATE TABLE PRODUCT(
	CODE INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE FLOAT(8,2) NOT NULL,
    CATEGORY INT NOT NULL,
    
    PRIMARY KEY(CODE),
    
    FOREIGN KEY(CATEGORY) REFERENCES CATEGORY(CODE)
    ON UPDATE CASCADE
);

INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Apple 13-inch MacBook Pro', 'New processors and graphics', 835.00, 1);
INSERT INTO PRODUCT(NAME, PRICE, CATEGORY) VALUES('Samsung ATIV Book 4', 724.00, 1);
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('TV LG 42LN540V 42-inch', 'Full HD LED TV', 349.00, 2);
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Samsung UE3LG5000 32-
inch', 'Full HD LED TV', 248.00, 2);
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Samsung Galaxy SIII', 'Sim Free Unlocked', 350, 4);
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Apple iPhone 5S','Unloked', 550, 4);
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Apple iPad Mini 16GB Wi-Fi','White', 300, 3);
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Google Nexus 7 7-inch','2GB RAM', 300, 3);

-- ---------------------------------------------------

CREATE TABLE CLIENT (
	CODE INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (32) NOT NULL,
    SURNAMES VARCHAR (60) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    PHONE INT(10),
    MAIL VARCHAR(60) NOT NULL UNIQUE,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100) NOT NULL,
    P_CODE INT (10),
    COUNTRY VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (CODE)
);

INSERT INTO CLIENT(NAME,SURNAMES,DNI,MAIL,CITY,COUNTRY) VALUES ('John', 'Smith', '12345678k','j@a.com','Palma', 'España');
INSERT INTO CLIENT(NAME,SURNAMES,DNI,MAIL,CITY,COUNTRY) VALUES ('Mike', 'Garnet', '11111111L','m@b.com','Palma de Mallorca', 'Spain');


-- ----------------------------------------------------------

CREATE TABLE SALE(
	CODE_PRODUCT INT NOT NULL,
    CODE_CLIENT INT NOT NULL,
    BUY_DATE DATE NOT NULL,
    QUANTITY INT(3) NOT NULL,
    
    
    PRIMARY KEY (CODE_PRODUCT, CODE_CLIENT),
    
    FOREIGN KEY (CODE_PRODUCT) REFERENCES PRODUCT(CODE)
    ON UPDATE CASCADE,
    
    FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENT(CODE)
    ON UPDATE CASCADE
);

INSERT INTO SALE(CODE_PRODUCT, CODE_CLIENT, BUY_DATE, QUANTITY) VALUES (6,1,'2014/01/01',1);
INSERT INTO SALE(CODE_PRODUCT, CODE_CLIENT, BUY_DATE, QUANTITY) VALUES (4,1,'2014/02/01',1);
INSERT INTO SALE(CODE_PRODUCT, CODE_CLIENT, BUY_DATE, QUANTITY) VALUES (5,1,'2014/02/01',2);
INSERT INTO SALE(CODE_PRODUCT, CODE_CLIENT, BUY_DATE, QUANTITY) VALUES (8,2,'2014/02/01',1);

-- ----------------------------------------------------------------------------------------------------

-- CAMBIOS A LAS TABLAS

-- MODIFICAR COLUMNA
ALTER TABLE CLIENT
MODIFY COLUMN DNI VARCHAR(9) NOT NULL UNIQUE;

-- AÑADIR COLUMNA
ALTER TABLE PRODUCT
ADD STOCK INT(5) DEFAULT 0; 

-- CAMBIANDO VALOR DE UNA COLUMNA
UPDATE PRODUCT SET STOCK = 5 WHERE PRODUCT.CODE >0;

SELECT * FROM PRODUCT;

-- ------------------------------- TESTS
-- ERROR PORQUE DNI REPETIDO
INSERT INTO CLIENT(NAME,SURNAMES,DNI,MAIL,CITY,COUNTRY) VALUES ('Mary', 'Smith', '12345678k','m@a.com','Inca', 'España');

-- ERROR PORQUE HACE FALTA AÑADIR APELLIDO
INSERT INTO CLIENT(NAME,DNI,MAIL,CITY,COUNTRY) VALUES ('Barbara', '87654321J','b@a.com','Inca', 'España');

-- ERROR PORQUE EN LA TABLA CLIENTE NO EXISTE LA COLUMNA STOCK
INSERT INTO CLIENT(NAME,SURNAMES,DNI,MAIL,CITY,COUNTRY, STOCK) VALUES ('Sussan', 'Collin', '87654321J','s@a.com','Inca', 'España');

-- NIGÚN ERROR
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Apple 15-inch MacBook Pro','New processors and graphics', 1200.00, 1);

-- NO DEJA AÑADIR EL PRODUCTO PORQUE NO EXISTE UNA CATEGORIA CON UN CODIGO IGUAL A 5
INSERT INTO PRODUCT(NAME, DESCRIPTION, PRICE, CATEGORY) VALUES('Apple 17-inch MacBook Pro','New processors and graphics', 1400.00, 5);



-- ------------------------------- SELECTS

-- Show how many products we have for every category
SELECT
	COUNT(*) AS CANTIDAD, CATEGORY.NAME
FROM
	PRODUCT, CATEGORY
WHERE
PRODUCT.CATEGORY=CATEGORY.CODE
GROUP BY CATEGORY;

-- Show all the clients who have'nt buy anything

SELECT
	*
FROM
	CLIENT
WHERE
	CODE NOT IN (SELECT
					DISTINCT CODE_CLIENT
				FROM
					SALE, CLIENT
				WHERE
					SALE.CODE_CLIENT = CLIENT.CODE);

-- Show for every product the total amount we have sold.
SELECT
    SUM(SALE.QUANTITY) AS QUANTITY_SOLD,
    PRODUCT.NAME
FROM
	SALE, PRODUCT
WHERE
	SALE.CODE_PRODUCT = PRODUCT.CODE
GROUP BY CODE_PRODUCT;

SELECT
	*
FROM
	PRODUCT;
-- Show the clients who have bought a phone
(SELECT
	CATEGORY.CODE
FROM
	CATEGORY
WHERE
	CATEGORY.NAME = 'PHONES');
    
SELECT
	concat(CLIENT.SURNAMES, ", ", CLIENT.NAME) AS CLIENT
FROM
	SALE, CLIENT
WHERE
	SALE.CODE_CLIENT = CLIENT.CODE AND
    SALE.CODE_PRODUCT = (SELECT
							CATEGORY.CODE
						FROM
							CATEGORY
						WHERE
							CATEGORY.NAME = 'PHONES');

-- Show all the products for the LG brand. Check the result. Is it correct?. How we can solve this problem. Try to do it.
    
CREATE TABLE BRAND(
	CODE INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    
    PRIMARY KEY(CODE)
);

INSERT INTO BRAND(NAME) VALUES ('APPLE');
INSERT INTO BRAND(NAME) VALUES ('SAMSUNG');
INSERT INTO BRAND(NAME) VALUES ('LG');
INSERT INTO BRAND(NAME) VALUES ('GOOGLE');

SELECT * FROM PRODUCT;



ALTER TABLE PRODUCT
ADD COLUMN BRAND INT ;

ALTER TABLE PRODUCT
ADD FOREIGN KEY (BRAND) REFERENCES BRAND(CODE) ON UPDATE CASCADE;

UPDATE PRODUCT SET BRAND = 4 WHERE CODE = 8;

SELECT
	*
FROM
	PRODUCT, BRAND
WHERE
	PRODUCT.BRAND = BRAND.CODE AND
	BRAND.NAME = 'LG';