

INSERT INTO AUTOR(IDAUTOR, NOM) 
VALUES
	(1,'AUTOR1'), 
    (2,'AUTOR2'),
    (3,'AUTOR SENSE LLIBRES');

ALTER TABLE LLIBRE 
MODIFY COLUMN IDAUTOR INT;

INSERT INTO LLIBRE(IDLLIBRE, NOM, IDAUTOR) 
VALUES
	(1,'LLIBRE1',1), 
    (2,'LLIBRE2',2),
    (3,'AUTOR SENSE LLIBRES', NULL);
    
    
-- -------------------------------------------------------------------
-- INNER JOIN
SELECT
	*
FROM
	AUTOR, LLIBRE
WHERE
	AUTOR.IDAUTOR = LLIBRE.IDAUTOR;

    
SELECT
	*
FROM
	AUTOR INNER JOIN LLIBRE ON AUTOR.IDAUTOR = LLIBRE.IDAUTOR;
    
    
-- ----------------------------------OUTER JOIN
-- LEFT
(SELECT
	*
FROM
	AUTOR LEFT JOIN LLIBRE ON AUTOR.IDAUTOR = LLIBRE.IDAUTOR);

-- RIGHT
(SELECT
	*
FROM
	AUTOR RIGHT JOIN LLIBRE ON AUTOR.IDAUTOR = LLIBRE.IDAUTOR);
    
-- FULL

/* NO MYSQL
SELECT
	*
FROM
	AUTOR FULL JOIN LLIBRE ON AUTOR.IDAUTOR = LLIBRE.IDAUTOR;*/


(SELECT
	*
FROM
	AUTOR LEFT JOIN LLIBRE ON AUTOR.IDAUTOR = LLIBRE.IDAUTOR)
UNION ALL
(SELECT
	*
FROM
	AUTOR RIGHT JOIN LLIBRE ON AUTOR.IDAUTOR = LLIBRE.IDAUTOR)